version: "3.1"
services:

  archib-eureka:
    image: archib-eureka
    build:
      context: ./
      dockerfile: ./eureka-service/Dockerfile
    container_name: archib-eureka
    ports:
      - "8761:8761"
    environment:
      - SERVER_PORT=8761
      - EUREKA_CLIENT_REGISTERWITHEUREKA=false
      - EUREKA_CLIENT_FETCHREGISTRY=false
      - EUREKA_INSTANCE_HOSTNAME=192.168.99.101
      
  archib-hystrix-monitor:
    image: archib-hystrix-monitor
    build:
      context: ./
      dockerfile: ./hystrix-monitor/Dockerfile
    container_name: archib-hystrix-monitor
    ports:
      - "8989:8989"
    environment:
      - SERVER_PORT=8989
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.99.101:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=192.168.99.101
      
  archib-hystrix-client:
    image: archib-hystrix-client
    build:
      context: ./
      dockerfile: ./hystrix-client/Dockerfile
    container_name: archib-hystrix-client
    ports:
      - "8072:8072"
    environment:
      - SPRING_APPLICATION_NAME=helloclient
      - SERVER_PORT=8072
      - MC_SERVER_NAME=helloserver
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.99.101:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=192.168.99.101
      - HYSTRIX_COMMAND_HELLO_EXECUTION_ISOLATION_THREAD_TIMEOUTINMILLISECCONDS=1000
      - HYSTRIX_COMMAND_HELLO_EXECUTION_ISOLATION_STRATEGY=THREAD
      - HYSTRIX_COMMAND_HELLO_CIRCUITBREAKER_ENABLED=true
      - HYSTRIX_COMMAND_HELLO_CIRCUITBREAKER_REQUEST_VOLUMETHRESHOLD=10
      - HYSTRIX_COMMAND_HELLO_CIRCUITBREAKER_SLEEPWINDOWINMILLISECONDS=10000
      
  archib-hystrix-server:
    image: archib-hystrix-server
    build:
      context: ./
      dockerfile: ./hystrix-server/Dockerfile
    container_name: archib-hystrix-server
    ports:
      - "8071:8071"
    environment:
      - SPRING_APPLICATION_NAME=helloserver
      - SERVER_PORT=8071
      - EUREKA_CLIENT_REGISTERWITHEUREKA=true
      - EUREKA_CLIENT_FETCHREGISTRY=true
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://192.168.99.101:8761/eureka
      - EUREKA_INSTANCE_HOSTNAME=192.168.99.101
